Repository osscameroon/onacut, pull requests merged in 2022-11, with the labels that each got.

#151 feat(fast-api): code + test + ci
  .github/workflows/fastapi-ci.yaml
  backend/onacut.sql
  fastapi/.gitignore
  fastapi/Makefile
  fastapi/onacut/common.py
  fastapi/onacut/main.py
  fastapi/onacut/routers/alerts.py
  fastapi/onacut/routers/cities.py
  fastapi/onacut/routers/districts.py
  fastapi/onacut/routers/regions.py
  fastapi/onacut/schemas/alert.py
  fastapi/onacut/schemas/districts.py
  fastapi/onacut/schemas/region.py
  fastapi/onacut/tests/__init__.py
  fastapi/onacut/tests/fixtures/test_sqlite.data
  fastapi/onacut/tests/routers/conftest.py
  fastapi/onacut/tests/routers/test_alerts.py
  fastapi/onacut/tests/routers/test_cities.py
  fastapi/onacut/tests/routers/test_districts.py
  fastapi/onacut/tests/routers/test_regions.py
  fastapi/onacut/tests/schemas/.gitkeep
  fastapi/onacut/tests/test_alerts.py
  fastapi/onacut/tests/test_cities.py
  fastapi/onacut/tests/test_common.py
  fastapi/onacut/tests/test_districts.py
  fastapi/onacut/tests/test_regions.py
  fastapi/requirements-dev.txt
  fastapi/requirements.txt
Labels: need review

#167 fix(fastapi): fix the cors issue on the backend when calling from another host (wildcard(*))
  fastapi/onacut/main.py
Labels: need review

#161 Add other fields when adding an alert
  frontend/package-lock.json
  frontend/src/pages/addAlert/addAlert.tsx
  frontend/src/translations/en.ts
  frontend/src/translations/fr.ts
Labels: frontend

#168 Add new fields on AlertSchema
  fastapi/onacut/dependencies.py
  fastapi/onacut/models.py
  fastapi/onacut/routers/alerts.py
  fastapi/onacut/routers/cities.py
  fastapi/onacut/routers/districts.py
  fastapi/onacut/routers/regions.py
  fastapi/onacut/schemas/alert.py
  fastapi/onacut/tests/fixtures/test_sqlite.data
  fastapi/onacut/tests/routers/test_alerts.py
Labels: need review

#169 Connect to the new backend
  frontend/package.json
  frontend/src/config.ts
  frontend/src/pages/detail/Detail.page.tsx
  frontend/src/pages/list/List.page.tsx
  frontend/src/pages/streetMap/StreetMap.page.tsx
  frontend/src/routes/index.tsx
  frontend/src/services/api/AlertService.ts
Labels: frontend, need review
